# Generated by Django 5.1.3 on 2025-02-12 23:20

from django.db import migrations
from django.contrib.auth.models import User

def create_default_provider(apps, schema_editor):
    UserProfile = apps.get_model('myapp', 'UserProfile')
    JobProviderProfile = apps.get_model('myapp', 'JobProviderProfile')
    JobPosting = apps.get_model('myapp', 'JobPosting')
    User = apps.get_model('auth', 'User')
    
    # Create default user if needed
    user, _ = User.objects.get_or_create(
        username='default_provider',
        defaults={'email': 'default@example.com'}
    )
    
    # Create default user profile
    user_profile, _ = UserProfile.objects.get_or_create(
        user=user,
        defaults={
            'is_job_provider': True,
            'account_holder_name': 'Default Provider'
        }
    )
    
    # Create default job provider profile
    provider, _ = JobProviderProfile.objects.get_or_create(
        user_profile=user_profile,
        defaults={
            'company_description': 'Default Company'
        }
    )
    
    # Update all job postings without a provider
    JobPosting.objects.filter(provider__isnull=True).update(provider=provider)

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):
    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_provider, reverse_func),
    ]
