# Generated by Django 5.1.3 on 2025-04-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_jobposting_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
