# Generated by Django 5.1.3 on 2024-12-19 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_jobposting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='graduation_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='reference_contact',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='reference_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='reference_relation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='school_name',
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='myapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relation', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='myapp.userprofile')),
            ],
        ),
    ]
