# Generated by Django 5.1.3 on 2025-06-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_jobposting_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_job_provider',
            field=models.BooleanField(default=True),
        ),
    ]
