# Generated by Django 5.1.3 on 2025-06-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_userprofile_is_job_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorited_jobs',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='myapp.jobposting'),
        ),
    ]
