# Generated by Django 5.1.3 on 2025-02-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_userprofile_graduation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
