# Generated by Django 5.1.3 on 2025-06-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_userprofile_favorited_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='num_applications',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
