# Generated by Django 5.1.3 on 2025-06-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_jobposting_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='applied_jobs',
            field=models.ManyToManyField(blank=True, related_name='applicants', to='myapp.jobposting'),
        ),
    ]
