# Generated by Django 5.1.3 on 2025-06-21 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_badge_userprofile_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='criteria',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress', models.JSONField(default=dict)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_challenges', to='myapp.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_challenges', to='myapp.userprofile')),
            ],
            options={
                'unique_together': {('user', 'challenge')},
            },
        ),
    ]
