# Generated by Django 5.1.3 on 2025-06-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_challenge_criteria_userchallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='currently_working',
            field=models.BooleanField(default=False),
        ),
    ]
